- name: Create directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory
    owner: ubuntu

- name: Copy compressed backend folder
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    owner: ubuntu

- name: Run the web server
  become: true
  shell: |
    su - ubuntu -c 'cd /home/ubuntu/backend && npm install'  # Runs PM2 stop as 'ubuntu' user
    su - ubuntu -c 'cd /home/ubuntu/backend && pm2 stop backend || true'  # Runs PM2 stop as 'ubuntu' user
    su - ubuntu -c 'cd /home/ubuntu/backend && pm2 delete backend || true'  # Runs PM2 delete as 'ubuntu' user
    su - ubuntu -c 'cd /home/ubuntu/backend && pm2 start npm --name "backend" -- start'  # Starts PM2 as 'ubuntu' user
  register: web_server_output

- name: Output result from 'Run the web server'
  debug:
    var: web_server_output
