---
- name: Create directory
  become: true
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy compressed backend folder
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    owner: ubuntu

- name: Run the web server
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install
    pm2 stop backend || true  # The || true ensures that the playbook does not fail if the process does not exist
    pm2 delete backend || true
    pm2 start npm --name "backend" -- start
